package org.alexmond.gotmpl4j.html;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;

import org.junit.jupiter.api.Test;

import org.alexmond.gotmpl4j.GoTemplate;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Conformance suite ported from Go {@code html/template}'s content_test.go
 * {@code TestTypedContent} table. It renders a matrix: each template (a single
 * {@code {{.}}} in some HTML / CSS / JS / URL context) against nine <em>typed</em>
 * content values — a plain string plus
 * {@code template.CSS}/{@code HTML}/{@code HTMLAttr}/{@code JS}/{@code JSStr}/
 * {@code URL}/{@code Srcset}, modelled here by {@link SafeContent}. Each case asserts
 * that gotmpl4j either passes the typed content through (when the context matches its
 * safe kind) or emits the {@code ZgotmplZ} filter-failsafe (when it doesn't),
 * byte-for-byte with Go.
 *
 * <p>
 * Fixtures are generated by {@code .claude/scripts/conformance/content_extract.go}, which
 * renders every (template, value) pair through the real {@code html/template} engine for
 * ground truth. Each TSV row is {@code base64(input) \t base64(output) \t dataIndex},
 * where {@code dataIndex} selects the matching value from {@link #data()} (index-aligned
 * with the generator's {@code data} slice).
 */
class HtmlTypedContentConformanceTest {

	/** Index-aligned with content_extract.go's {@code data []any}. */
	private static Object[] data() {
		return new Object[] { "<b> \"foo%\" O'Reilly &bar;", SafeContent.css("a[href =~ \"//example.com\"]#foo"),
				SafeContent.html("Hello, <b>World</b> &amp;tc!"), SafeContent.htmlAttr(" dir=\"ltr\""),
				SafeContent.js("c && alert(\"Hello, World!\");"), SafeContent.jsStr("Hello, World & O'Reilly\\u0021"),
				SafeContent.url("greeting=H%69,&addressee=(World)"),
				SafeContent.srcset("greeting=H%69,&addressee=(World) 2x, https://golang.org/favicon.ico 500.5w"),
				SafeContent.url(",foo/,") };
	}

	@Test
	void typedContentConformance() throws Exception {
		Object[] data = data();
		List<Case> cases = load();
		assertFalse(cases.isEmpty(), "no typed-content cases loaded");
		List<String> failures = new ArrayList<>();
		for (Case c : cases) {
			String got;
			try {
				GoTemplate t = GoTemplate.builder().htmlEscaping().build();
				t.parse("tc", c.input());
				got = t.render("tc", data[c.dataIndex()]);
			}
			catch (Exception | StackOverflowError ex) {
				got = "<<threw " + ex.getClass().getSimpleName() + ": " + ex.getMessage() + ">>";
			}
			if (!c.expected().equals(got)) {
				failures.add(String.format("[%s | data#%d]%n  want: %s%n  got:  %s", c.input(), c.dataIndex(),
						c.expected(), got));
			}
		}
		assertTrue(failures.isEmpty(), () -> "html/template typed-content conformance failures (" + failures.size()
				+ "/" + cases.size() + "):\n" + String.join("\n", failures));
	}

	private static List<Case> load() throws Exception {
		List<Case> cases = new ArrayList<>();
		try (BufferedReader r = new BufferedReader(new InputStreamReader(
				HtmlTypedContentConformanceTest.class.getResourceAsStream("/html/html_typed_content_cases.tsv"),
				StandardCharsets.UTF_8))) {
			String line;
			while ((line = r.readLine()) != null) {
				if (line.isEmpty()) {
					continue;
				}
				String[] p = line.split("\t", 3);
				cases.add(new Case(decode(p[0]), decode(p[1]), Integer.parseInt(p[2])));
			}
		}
		return cases;
	}

	private static String decode(String b64) {
		return new String(Base64.getDecoder().decode(b64), StandardCharsets.UTF_8);
	}

	private record Case(String input, String expected, int dataIndex) {
	}

}
